### ISSUE TITLE
reaction2gene.txt not found

### ISSUE THREAD

**Issue by marieBvr** [PathwayCommons/chibe#68]
Hi,

I cloned chibe project from git repository.
I followed the Setup Guide to compile.
When I run the _query / PathwayCommons (in BioPAX) / Find enriched Pathway_ I get the error :
```
java.io.FileNotFoundException: /home/mlefebvre/Documents/Lib/chibe/portal-cache/pathway2gene.txt (Aucun fichier ou dossier de ce type)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at org.gvt.action.EnrichedPathwaysAction.getPathways(EnrichedPathwaysAction.java:146)
	at org.gvt.action.EnrichedPathwaysAction.run(EnrichedPathwaysAction.java:40)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:996)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:538)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:488)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:400)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:809)
	at org.eclipse.jface.window.Window.open(Window.java:787)
	at org.gvt.ChisioMain.main(ChisioMain.java:199)
java.lang.NullPointerException
	at org.gvt.action.EnrichedPathwaysAction.run(EnrichedPathwaysAction.java:45)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:996)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:538)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:488)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:400)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:809)
	at org.eclipse.jface.window.Window.open(Window.java:787)
	at org.gvt.ChisioMain.main(ChisioMain.java:199)
java.io.FileNotFoundException: /home/mlefebvre/Documents/Lib/chibe/portal-cache/reaction2gene.txt (Aucun fichier ou dossier de ce type)
(...)
```

Any idea how to solve this ?

Thanks
Marie

**Comment by ozgunbabur** [comment]
Hi Marie, yes, those features are not up-to-date with the latest version of
Pathway Commons. I am on it and will notify you when fixed.

**Comment by ozgunbabur** [comment]
Marie, it should be fixed now. You need to update the project. But before
testing it, you also need to find and remove the file "chibe-conf.txt". It
will be recreated when ChiBE runs. It can either be in your project folder,
or under ".chibe" folder under your home folder.

**Comment by marieBvr** [comment]
I followed your instructions and it worked !
Thanks
